name: maxta_todo_list
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  page_transition: ^2.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  
  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  
  
  
  
  
  
  
  
  
  
